apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
  namespace: sooraj
  labels:
    app: nginx-resolver
spec:
  containers:
  - name: nginx-resolver
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver-service
  namespace: sooraj
spec:
  type: ClusterIP
  selector:
    app: nginx-resolver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
